export const boroughs = [
  "Tout le Grand Montréal",
  "Ahuntsic-Cartierville",
  "Anjou",
  "Boucherville",
  "Brossard",
  "Candiac",
  "Châteauguay",
  "Côte-des-Neiges–Notre-Dame-de-Grâce",
  "La Prairie",
  "Lachine",
  "Lasalle",
  "Le Sud-Ouest",
  "Longueuil",
  "L'Île-Bizard–Sainte-Geneviève",
  "Mercier–Hochelaga-Maisonneuve",
  "Montréal-Nord",
  "Outremont",
  "Pierrefonds-Roxboro",
  "Plateau-Mont-Royal",
  "Rivière-des-Prairies–Pointe-aux-Trembles",
  "Rosemont–La Petite-Patrie",
  "Saint-Constant",
  "Saint-Hubert",
  "Saint-Lambert",
  "Saint-Léonard",
  "Verdun",
  "Ville-Marie",
  "Villeray–Saint-Michel–Parc-Extension"
];

